In [4]:
import numpy as n 
n.array(type([10,20,30,40,50]))


array(<class 'list'>, dtype=object)

In [8]:
import numpy as n 
n.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
import numpy as n 
aee=n.array([7,8,9],dtype=float)
print(type(aee))

<class 'numpy.ndarray'>


In [18]:
import numpy as n 
arr1=n.zeros(6)
arr2=n.zeros((3,2),dtype=int)
print(arr1,arr2)

[0. 0. 0. 0. 0. 0.] [[0 0]
 [0 0]
 [0 0]]


In [19]:
import numpy as np 
np.empty((2,2))  //it gives garbage values and empty allocates free space so prefered over zeros and  the garbage values will be there before in zeros it is replaced so it is faster 

array([[2.12199579e-314, 1.09919382e-311],
       [6.22522714e-321, 1.09919382e-311]])

In [23]:
import numpy as n 
n.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
import numpy as n 
n.linspace(0,1,6)  //in inspace the 1 is inclusive but not in arange it is inclusive 

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
import numpy as n 
n.random.random((3,3))

array([[0.7936571 , 0.90941421, 0.41518147],
       [0.89725201, 0.7680489 , 0.27030422],
       [0.88883154, 0.08941892, 0.12925151]])

In [3]:
import numpy as np
arr = np.arange(1, 21).reshape(4, 5)
print("Array:\n", arr)
print("Number of dimensions :", arr.ndim)
print("Shape :", arr.shape)
print("Size :", arr.size)
print("Data type :", arr.dtype)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Number of dimensions : 2
Shape : (4, 5)
Size : 20
Data type : int32


In [17]:
import numpy as n
x=n.arange(50)
print(x)
print(x.size)
print(x.nbytes)
np.random.seed(0)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
50
200


In [41]:
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr[2,3])
print(arr[:,3])
print(arr[2,:])
a=arr[-1,:].reshape((4,1))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 4  8 12]
[ 9 10 11 12]
[[ 9]
 [10]
 [11]
 [12]]


In [39]:
import numpy as np
x=np.arange(12).reshape((3,4))
print(x)
row=np.vsplit(x,[2])
col=np.hsplit(x,[2])
print(row)
print(col)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
